### ISSUE TITLE
Stuck at step 2 of setting up VFIO

### ISSUE THREAD

**Issue by bananasmoothii** [ryanprescott/realtek-verb-tools#7]
Hello,

In step 2 of setting up VFIO you use the command 'kernelstub', but I don't have it on manjaro.
I tried to install it with [this](https://github.com/isantop/kernelstub) but now, here is what I get:
```
[myName@MachineABanane2 kernelstub]$ sudo kernelstub -a "pci-stub.ids=8086:02c8 iommu=pt intel_iommu=on"
kernelstub           : ERROR    Can't find the kernel image! 

 Please use the --kernel-path option to specify the path to the kernel image
NoneType: None
[myName@MachineABanane2 kernelstub]$ sudo kernelstub -a "pci-stub.ids=8086:02c8 iommu=pt intel_iommu=on" --kernel-path /home/myName/vm/win10.iso
kernelstub           : ERROR    Can't find the initrd image! 

 Please use the --initrd-path option to specify the path to the initrd image
NoneType: None
[myName@MachineABanane2 kernelstub]$ sudo kernelstub -a "pci-stub.ids=8086:02c8 iommu=pt intel_iommu=on" --kernel-path /home/myName/vm/win10.iso --initrd-path /home/myName/vm/win10.img
kernelstub.Installer : ERROR    Couldn't copy the kernel onto the ESP!
This is a critical error and we cannot continue. Check your settings to see if there is a typo. Otherwise, check permissions and try again.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 261, in copy_files
    shutil.copy(src, dest)
  File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 276, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.9/shutil.py", line 166, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.9/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: '/home/myName/vm/win10.iso' -> '/boot/efi/EFI/Manjaro_Linux-9ffb3081-78d3-4e75-9dba-86d6360f6459/vmlinuz.efi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 134, in setup_kernel
    self.copy_files(
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 265, in copy_files
    raise FileOpsError("Could not copy one or more files.")
kernelstub.installer.FileOpsError: Could not copy one or more files.
[myName@MachineABanane2 kernelstub]$ sudo kernelstub -a "pci-stub.ids=8086:02c8 iommu=pt intel_iommu=on" --kernel-path /home/myName/vm/win10.img --initrd-path /home/myName/vm/win10.iso
kernelstub.Installer : ERROR    Couldn't copy the kernel onto the ESP!
This is a critical error and we cannot continue. Check your settings to see if there is a typo. Otherwise, check permissions and try again.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 261, in copy_files
    shutil.copy(src, dest)
  File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 276, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.9/shutil.py", line 166, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.9/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: '/home/myName/vm/win10.img' -> '/boot/efi/EFI/Manjaro_Linux-9ffb3081-78d3-4e75-9dba-86d6360f6459/vmlinuz.efi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 134, in setup_kernel
    self.copy_files(
  File "/usr/lib/python3.9/site-packages/kernelstub/installer.py", line 265, in copy_files
    raise FileOpsError("Could not copy one or more files.")
kernelstub.installer.FileOpsError: Could not copy one or more files.
```
Thanks in advance !

**Comment by ryanprescott** [comment]
Hi there!

On other systems you should be editing the kernel parameters manually:

https://archived.forum.manjaro.org/t/edit-kernel-commands-how/81572

**Comment by bananasmoothii** [comment]
Thanks for responding that fast ! but now I'm stuck at 3 of capturing verbs: I can't start my VM, it gives me this error:
```
(qemu) qemu-system-x86_64: -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true: vfio 0000:00:1f.3: failed to open /dev/vfio/14: No such file or directory
```

**Comment by bananasmoothii** [comment]
Or if not using sudo, I get
```
(qemu) qemu-system-x86_64: -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true: vfio 0000:00:1f.3: failed to open /dev/vfio/14: Permission denied
```
I looked at the /dev/vfio/14 file, it is empty, and it belongs to the "root" group

**Comment by bananasmoothii** [comment]
Also, if that helps, if I restart with the settings I set with this:
> https://archived.forum.manjaro.org/t/edit-kernel-commands-how/81572

It shows that there is no sound device. Before it showed a sound device, even if it was not working

**Comment by bananasmoothii** [comment]
Hello again,
I'm sorry to bother you with that but you're my only hope lol.
I'm thinking about another solution: what if I test the verbs _you_ got ? Because our sound cards are pretty similar, mine is `00:1f.3 Audio device: Intel Corporation Comet Lake PCH-LP cAVS`

**Comment by bananasmoothii** [comment]
Or maybe, I could try to test all possible verbs, the thing is, there are 1,048,576 combinations to `0x20 0xNNN 0xNN` where `N` is a hexadecimal digit between 0 and f (16), so maybe you know parts of the verb that won't change, meaning the verb must contain some numbers to be a sound verb (or I don't know how you would call that), but here I need your knowledge again. Thanks in advance and sorry for being a little bit spammy !

**Comment by JonAnCla** [comment]
Hey you should check that you have vfio working correctly - following should show output saying that your audio card is bound on the requested pci address 
`sudo dmesg | grep vfio`

Also I found that I had to specify the kernel params differently to what is in the README. I used `vfio-pci.ids=8086:a348` instead of "pci-stub.ids=8086:a348"

Good luck!

**Comment by bananasmoothii** [comment]
Thanks for the answer !
Unfortunately it still doesn't work. With `vfio-pci.ids=` now linux shows that there is a sound output device, but when I run the script (vfio-bind.sh), it does as if I unplugged it.
`sudo dmesg | grep -i vfio` gives
```
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.13-x86_64 root=UUID=9ffb3081-78d3-4e75-9dba-86d6360f6459 rw quiet apparmor=1 security=apparmor udev.log_priority=3 vfio-pci.ids=8086:02c8 iommu=pt intel_iommu=on
[    0.044699] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.13-x86_64 root=UUID=9ffb3081-78d3-4e75-9dba-86d6360f6459 rw quiet apparmor=1 security=apparmor udev.log_priority=3 vfio-pci.ids=8086:02c8 iommu=pt intel_iommu=on
[  142.068113] VFIO - User Level meta-driver version: 0.3
[  142.091854] vfio_pci: add [8086:02c8[ffffffff:ffffffff]] class 0x000000/00000000
```

**Comment by bananasmoothii** [comment]
I forgot to mention: when I run the vfio-bind script, I get `./vfio-bind.sh: ligne 9 : echo: erreur d'écriture : Le fichier existe
` which mean "line 9: echo: write error: the file exists". And when running the startvm script, I now get: `qemu-system-x86_64: -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true: vfio 0000:00:1f.3: failed to open /dev/vfio/14: No such file or directory` . Now, `/dev/vfio` contains only one empty file called "vfio"

**Comment by bananasmoothii** [comment]
Up!
![gif](https://c.tenor.com/5FAYuypOiKcAAAAM/cat-please.gif)
Maybe I should do that in an Ubuntu partition so it has more chances to work ?

**Comment by bananasmoothii** [comment]
Hello again, I installed Ubuntu, now I have this
```
$ sudo qemu-system-x86_64 -enable-kvm -hda win10.img -m 4G -smp 4 -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true -trace events=./events.txt -monitor stdio -usb -device usb-host,hostbus=01,hostport=6
QEMU 5.2.0 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: -device vfio-pci,host=0000:00:1f.3,x-no-mmap=true: vfio 0000:00:1f.3: group 14 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
```

**Comment by bananasmoothii** [comment]
@hottwaj @ryanprescott I hate to ping you but if would be so cool if you responded...

**Comment by JonAnCla** [comment]
I think that's covered in the docs here:
https://github.com/ryanprescott/realtek-verb-tools/wiki/How-to-sniff-verbs-from-a-Windows-sound-driver#troubleshooting

**Comment by bananasmoothii** [comment]
woops, indeed... thanks, it seems to work now, I'll continue tomorrow

**Comment by bananasmoothii** [comment]
Hi, thanks a lot ! Now I was able to get into the windows vm and play a music inside it that I could hear !

There is still a problem: `cleanverbs.py` doesn't output anything.
Here is my qemu-output:
[qemu-output.txt](https://github.com/ryanprescott/realtek-verb-tools/files/7331986/qemu-output.txt)

**Comment by bananasmoothii** [comment]
After finding [this thread](https://bugzilla.kernel.org/show_bug.cgi?id=207423#c19) that used a similar technique to this one, I think I should open an issue over there too. They have a qemu output very similar to mine, and ours are very different from what the regex in `cleanverbs.py` is awaiting. Also, for the output, I had to use `&>` and not just `>`. In the meantime, I have no clue about how to use the logs I got...
(@ryanprescott @hottwaj, I hope this is the last time 🙄)

**Comment by bananasmoothii** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=214707

**Comment by JonAnCla** [comment]
Sorry, I don't know how to help you.  I got output like the following from qemu which can be mapped to hda-verb commands, but it looks like you didn't get any verb output when you ran qemu, hence you got no output when you ran cleanverbs.py

```
CORB[1] = 0xf0000 (caddr:0x0 nid:0x0 control:0xf00 param:0x0)
CORB[2] = 0xf0002 (caddr:0x0 nid:0x0 control:0xf00 param:0x2)
CORB[3] = 0xf0004 (caddr:0x0 nid:0x0 control:0xf00 param:0x4)
RIRBWP advance to 3, last WP 0
CORB caddr:0x0 nid:0x0 control:0xf00 param:0x0 response:0x10ec0245 (ex 0x0)
CORB caddr:0x0 nid:0x0 control:0xf00 param:0x2 response:0x100001 (ex 0x0)
CORB caddr:0x0 nid:0x0 control:0xf00 param:0x4 response:0x10001 (ex 0x0)
```

**Comment by JonAnCla** [comment]
oh I just realised, your qemu output contains only lines with `vfio_region_write` because you captured the STDERR output from qemu using `&> qemu-output.txt`

but as mentioned in the docs, you want to capture STDOUT output from qemu using `> qemu-output.txt`

if you don't get any STDOUT output from qemu, then I don't know how to help you

**Comment by bananasmoothii** [comment]
I didn't compile qemu from source, I think that's why. I directly used qemu from the command line because I am getting errors when trying to compile qemu. I'll send them here once I get back home. Thanks for your help

**Comment by JonAnCla** [comment]
I can't help with any issues you have compiling.  Have a look at issues I and others came across here: https://github.com/ryanprescott/realtek-verb-tools/issues/1

**Comment by bananasmoothii** [comment]
Hello, I managed to compile qemu, but it didn't change anything.

**Comment by bananasmoothii** [comment]
Maybe this has something to do with the fact that I am using [ReviOS](https://revi.cc), a modified (lighter) windows ?

**Comment by bananasmoothii** [comment]
Well, let's see if that helps: https://gitlab.com/qemu-project/qemu/-/issues/668

**Comment by JonAnCla** [comment]
The verbs output is produced by the patches on the forked version of qemu that is pointed to in the docs of this repo. I don't think you will get help from qemu devs because they are not aware of those patches. 

Are you sure you used the  qemu you compiled from the fork and not the system version you had already installed?

I did all this on an ubuntu system. No idea what things might be like on other distros

**Comment by bananasmoothii** [comment]
Ohhh, that was my mistake ! I didn't see it is a custom build, I downloaded and compiled the official one ! I'll try it today, thanks !
Reading is always the part where I go too fast and miss things, same for exams 🙄

**Comment by bananasmoothii** [comment]
Hi, I can't manage to compile that qemu, I tried what you said in #1 now I can do ./configure but make -j4 gives me 
```
make: *** [/home/banana/vm/qemu/rules.mak:86 : disas/arm-a64.o] Error 1
make: *** Wating for non-finished tasks....
```
(translated from french)
I'm using Ubuntu

**Comment by bananasmoothii** [comment]
I GOT VERBS !!

I managed to compile qemu ([this way](https://github.com/ryanprescott/realtek-verb-tools/issues/1#issuecomment-943701813)) and to get verbs, the only weird thing is that windows (in qemu) is not producing any sound anymore with my compiled version, not the one in the wiki but [this one](https://github.com/clementperon/qemu/commits/jcs-hda-dma-v2), as referenced in #1 (although I didn't try the one in the wiki with python 2). I checked back with normal qemu, sound was here again.

Should I proceed testing the verbs I got or should I try something other until I get sound in windows ?

**Comment by JonAnCla** [comment]
Hey I found I didn't get sound with the custom qemu either, even though I got verbs out of it. I didn't test the "standard" qemu.

I was able to get mute and  mic mute leds working from the verbs. I was hoping to also use it to get my top speaker working (underneath speaker was already working) but I didn't find anything that could help in the verbs. There are thousands and it's hard to interpret them 

I noticed that the clean verbs script only captures verbs on nid 0x20, but you will want to see verbs sent to all nids. You should change the regex in that script to catch them all.

Good luck

**Comment by bananasmoothii** [comment]
Ok, will do !

**Comment by bananasmoothii** [comment]
Hello, I seems really like I am running into every possible issue...

Here is my [qemu-output.txt](https://github.com/ryanprescott/realtek-verb-tools/files/7354425/qemu3-output.txt), the issue is that
1. There are only two lines with `nid:0x20`, so I removed that condition from the script as you told me to.
2. There are no lines containing `control:0x4` or `control:0x5`. So I removed the second condition from the script, which makes it print every 1110 line as clean-verb. But none worked, with and without the `vfio-bind.sh` script being ran.

**Comment by bananasmoothii** [comment]
Little bit of progress: I installed [this driver pack](https://github.com/AlanFinotty/AAFDCHDriverMod) in my VM and rebooted it, and I was happy to hear sound even with that specific qemu. I got ~20 lines with the `nid=0x20` condition, 128 without, and 2016 without both condition. Sadly, nothing produced any sound.

**Comment by bananasmoothii** [comment]
Hi, I tried again with only `nid == 0x20` as condition, but still nope. Any idea @hottwaj @ryanprescott ?
Here is my new raw [qemu-output.txt](https://github.com/ryanprescott/realtek-verb-tools/files/7359648/qemu-output.txt) btw

**Comment by ryanprescott** [comment]
Closing due to inactivity
